name: Format code
on:
  pull_request:
  push:
    branches:
      - master
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  format_backend:
    name: Format with ruff
    runs-on: arc-runners-small
    timeout-minutes: 30
    steps:

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup PATH
        run: echo "/home/runner/.local/bin" >> $GITHUB_PATH
      - uses: ./.github/workflows/actions/prepare

      - run: poetry run ruff check --fix --unsafe-fixes --preview --exit-zero .

      - run: poetry run ruff format .

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          fetch: false
          default_author: github_actions
          message: 'Backend: Auto format'
          add: '.'
